import { Download, FileText, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const reports = [
  {
    id: "RPT-091",
    type: "CBK Tier 3 Credit Compliance",
    date: "2026-06-25",
    status: "Verified",
    author: "Compliance Bot",
  },
  {
    id: "RPT-090",
    type: "Data Protection Act 2019 Log",
    date: "2026-06-20",
    status: "Verified",
    author: "System",
  },
  {
    id: "RPT-089",
    type: "Quarterly SACCO Yield Report",
    date: "2026-06-15",
    status: "Pending Audit",
    author: "Wanjiku Njeri",
  },
  {
    id: "RPT-088",
    type: "Default Risk Exposure Summary",
    date: "2026-06-10",
    status: "Verified",
    author: "Risk Engine",
  },
];

export default function ReportsPage() {
  return (
    <main className="flex-1 overflow-y-auto bg-background px-4 md:px-8 py-8 relative w-full">
      <div className="max-w-6xl mx-auto space-y-8">
        <div className="flex flex-col gap-2">
          <h2 className="text-3xl font-bold text-foreground tracking-tight">
            Regulatory Reports
          </h2>
          <p className="text-muted-foreground">
            Compliance exports and audit trails for Central Bank and regulatory
            authorities.
          </p>
        </div>

        <Card className="shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between pb-4 border-b border-border/50">
            <CardTitle className="text-lg font-semibold flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              Generated Reports Archive
            </CardTitle>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" className="h-9 gap-2">
                <Filter className="w-4 h-4" />
                Filter
              </Button>
              <Button size="sm" className="h-9 gap-2">
                <Download className="w-4 h-4" />
                Export Batch CSV
              </Button>
            </div>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-30">Report ID</TableHead>
                  <TableHead>Document Type</TableHead>
                  <TableHead>Date Generated</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead className="text-right">Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell className="font-medium text-muted-foreground">
                      {report.id}
                    </TableCell>
                    <TableCell className="font-semibold">
                      {report.type}
                    </TableCell>
                    <TableCell>{report.date}</TableCell>
                    <TableCell>{report.author}</TableCell>
                    <TableCell className="text-right">
                      <span
                        className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${
                          report.status === "Verified"
                            ? "bg-emerald-500/10 text-emerald-500"
                            : "bg-amber-500/10 text-amber-500"
                        }`}
                      >
                        {report.status}
                      </span>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
